### ISSUE TITLE
Split email login and social login as separate components

### ISSUE THREAD

**Issue by polinom** [convoo/login-fire#10]
Ideally I see it having a bit more html like API. 

What do you think if we define it like so:

``` html
          <firebase-app
            name=""
            api-key=""
            auth-domain=""
            database-url="">
          </firebase-app>

          <login-fire  app-name="">
              <email-password reset-message="Check you email" auto-signup>
                   <input type="email">
                   <input type="password">
                   <input type="password-repeat">
                   <input type="extra-info">
              </email-password> 
              <anonymous></anonymous>
              <twitter></twitter>
              <github></github>
          </login-fire>

```

Then we can kind of have separated concerns. And do not mix one configuration attribute with element that have no relation to it.  

I know that would require a bit more of work. But I'm just curious if that is a good way of making components composable. 

Think about it as you would design some builtin html tag. Like a `<form>` for example.

**Comment by sbeleidy** [comment]
The issue is that I think we only need the customization for the email password setup. I'd prefer to have it the current way so that it's easy to just set everything up with one element. If the complexity increases we can switch to your proposed way.

The defaults can be made to be more than good enough for 90% of use cases and we can add customizability to make it possible to edit anything you need to.

Right now I think it's much nicer to be able to just do:

```
<login-fire 
  email-password
  anonymous 
  twitter
  github 
  app-name=""
  ></login-fire>
```

However, once we reach a more complex level I'm fine with switching to this approach. I think we would have something similar to the following setup:

``` html
<login-fire  app-name="">
  <email-password-fire 
    auto-signup
    tabbed
    confirm-password
    confirm-email
    password-reset-message="Check your email" 
    ></email-password-fire> 
  <social-provider-fire anonymous ></social-provider-fire>
  <social-provider-fire twitter ></social-provider-fire>
  <social-provider-fire github ></social-provider-fire>
  <social-provider-fire custom
    provider-url=""
    ></social-provider-fire>
</login-fire>
```

Is there anything that you want to expand on that the current setup is preventing you from doing?

**Comment by polinom** [comment]
That sounds good

No I have no problem with it right now... it's just that when I was adding `password-reset-message="Check your email"` then I though that it would be overkill for one element to have all configuration as attributes... 

Also I'm very curious what is a correct way for designing components.

**Comment by sbeleidy** [comment]
I definitely agree with your concern about one element with a ton of configuration but I think that should push us to have very good defaults. Being able to have a one line element for doing your entire authentication is what is so appealing about having this as a web component.

Regarding designing/structuring large components, I'm not really sure. I've seen how the [service worker elements](https://github.com/PolymerElements/platinum-sw) do things and it's interesting. It's somewhat like what you were suggesting but I'm not really sure when you should abstract it into child web components and when you should continue to add attributes.
