### ISSUE TITLE
Tabbed Sign Up vs Sign In interface

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#11]
We should have 2 different interfaces, one for sign up and one for sign in. This is definitely needed for email-password setup so that we can add password confirmation and potentially email confirmation.

This doesn't need to be through 2 literal tabs but could be done through a link that says "Sign up" which would show the extra inputs or "Sign In" which would remove them.

**Comment by sbeleidy** [comment]
We should also add a "tab" for reset password.

**Comment by masonlouchart** [comment]
Just to precise the "multi-tabs" part for sign in and sign up is done in the commit [590614a](https://github.com/convoo/login-fire/commit/590614a2382e2fe55aff860fef15a4590fcba8b4).

Maybe we could move the reset password part into another issue or update the title of this one?

**Comment by sbeleidy** [comment]
Reset password tab is also done. (The problem is that we didn't want to close issues that weren't merged in master yet but it seems to be getting out of hand. Really want to merge v2 soon so we can close all of these and launch the new release)

**Comment by masonlouchart** [comment]
If I'm not wrong, when an issue is fixed but not yet merged to the master the tag `ready` is set. And it is not on this one, that's why I was asking. 😉

**Comment by masonlouchart** [comment]
I think we're taking too much time to merge the v2. We shouldn't wait to have a perfect element to release a beautiful v1. Because developers think nothing is perfect and everything can be improved. Personally I'm wasting lot of time to re-re-re-read issues that are `ready` and search corresponding PR or commit. In addition, the milestone v1 is not progressing so it's not really motivating to work on the project.

Moreover, some issues are tagged `ready` but do not have much detail or link to any PR. 😕 

Feel free to share your thought about this subject 🤓 

Close this one because it's done.
_Milestone for v1 has too much opened issues already fixed._
