### ISSUE TITLE
Versions Mangement and Bower

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#161]
Hello guys,

I got an error with login-fire today `Cannot read property 'id' of undefined` and it was the same error as @masonlouchart about undefined provider.

So I try to bower update (and bower install login-fire) but couldn't get the new version of login-fire. 
Bower don't retrieve the latest version of the master branch if the version didn't change.

So what do you think about adding a CHANGELOG.md file with all changes and a section Unreleased (like in polymer-build : https://github.com/Polymer/polymer-build/blob/master/CHANGELOG.md) and bumping versions regularly ? (When there is a major fix, etc...) This means also creating a new tag (with git) when bumping new versions.

Cheers :tada:

**Comment by masonlouchart** [comment]
In fact Bower does not retrieve the version with the fix because it's not released. I'm targeting the branch `master` in a new project and it works.

I didn't want to make a new patch release because of the defined milestone and the new features already merged. But this is a major fix to apply so it will be a better decision to simply rename the milestone. Sometimes, I forget to use my brain you know...

**Comment by masonlouchart** [comment]
Hi @Oupsla !

The new release contains the fix for _"undefined provider"_.

Cheers.
