### ISSUE TITLE
Look into logout button as component

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#40]
There may be a way to logout the use with a button using https://firebase.google.com/docs/reference/node/firebase.auth.Auth#signOut . the issue is that it might not update the user and signedIn status of the login-fire components. We should look into it and test it out.

signOut function as part of login-fire should not be removed in favor of this but (if it works) this may make it simpler for some users.

**Comment by masonlouchart** [comment]
I think this issue is relating 2 pain points. The first one the ability to sign out easily and keeping the user status and representation sync through all `login-fire` elements. The second one is to have a simple component to show a sign-out button.

Do you agree with this?

The sign-out method is available since the [commit 107f06a5](https://github.com/convoo/login-fire/commit/107f06a5c115be324d3ef23bbbf68095d942ab4e) in the merged PR #47.
About a _"login-fire-signout-button"_ element there is an issue that could be a duplicate.
I would like to close this one in favor of the issue #55 .

What's your opinion?

**Comment by sbeleidy** [comment]
I think this was resolved by having the different sign out states for the buttons. We shouldn't need a separate element anymore.
