### ISSUE TITLE
Logout should have an icon

### ISSUE THREAD

**Issue by bkawk** [convoo/login-fire#54]
The spacing looks weird without an icon and as the social buttons have an icon I feel log out should also have one

**Comment by sbeleidy** [comment]
Maybe icons:exit-to-app but I think maybe we can make it point to the left instead of right?

![screen shot 2017-02-01 at 11 11 26 pm](https://cloud.githubusercontent.com/assets/1388511/22539048/376d3698-e8d4-11e6-84a0-affdfdec4b2b.png)

And another option: 
![screen shot 2017-02-01 at 11 15 20 pm](https://cloud.githubusercontent.com/assets/1388511/22539059/573758b4-e8d4-11e6-8881-df07ab04470e.png)

**Comment by bkawk** [comment]
We can flip it with css

**Comment by masonlouchart** [comment]
Maybe we should use the [exit-to-app icon](https://poly-icon.appspot.com/?name=myicons&size=24&icon=icons%3Aexit-to-app) as proposed instead of the [input icon](https://github.com/convoo/login-fire/blob/v2/icons.html#L50)?

**Comment by masonlouchart** [comment]
PR #128 merged.
