### ISSUE TITLE
Switch all this.$ to querySelector

### ISSUE THREAD

**Issue by sbeleidy** [convoo/login-fire#76]

**Comment by masonlouchart** [comment]
Can you add a description to this issue and an example of errors you got because of the selection by ID please?

IDs are supposed to be scoped and I can't imagine what kind of error we can get using `$` and solve by using `$$`.

**Comment by sbeleidy** [comment]
I'm not sure why the error happens but it happens when ids are in a `<template is="dom-if">` and you try to access them. Regardless of whether the if value is true or not.

What are you suggesting is the right way then? I'm a little confused.

**Comment by masonlouchart** [comment]
Actually, you can't reach an element inside a `dom-if` using its ID. I see why you want to replace the `$` usage by `$$` now.  IMHO, you can replace the `$` but it must be done case by case, not __all__ regardless the context. I was just worried by the word _"all"_ in the issue title. 🤐

**Comment by sbeleidy** [comment]
When would you want `this.$.id` instead of `this.$$("#id")` ?

**Comment by masonlouchart** [comment]
As much as possible.

In fact, I know only the `dom-if` element (and maybe others of the same kind like `iron-pages`) where it's not possible to use `this.$.id` simply because their children are not attached to the DOM by default but only in the virtual DOM.

For me, replace all `this.$.id` is like saying _"Polymer is not working"_. I think/guess/hope it works. 🤞

**Comment by sbeleidy** [comment]
I guess my logic is to just use something that's consistent and that will just work everywhere. Unless there's a benefit to `this.$.id` over `this.$$("#id")` I don't see a reason why switching all to `this.$$("#id")` is a bad idea. 

Sorry if you already answered this I just still don't get it. What's the benefit of this.$.id ?

**Comment by masonlouchart** [comment]
This is not a bad idea at all. I have just expressed my opinion. When I use a feature provided by a framework/language/tool and it seems not working as described in the documentation I have to understand why and _"fix it"_ (my code or the framework/language/tool) instead of avoid using it.

Also, I don't know if all (future) contributors will naturally apply this _"convention"_.

Just to be clear, I'm OK to replace `this.$.id` by querySelector. 😉 .

**Comment by sbeleidy** [comment]
As long as things are working I guess we shouldn't worry about this too much. Will close for now unless something else comes up.
