### ISSUE TITLE
locales.json is not `polymer build` friendly

### ISSUE THREAD

**Issue by mattpalermo** [convoo/login-fire#96]
When I run my project (which uses login-fire) through the `polymer build` command, the `locales.json` file is not copied into the `build` directory. This is solved by adding this file to the `extraDependencies` property of the `polymer.json` configuration. 

However, polymer build won't do anything special to the file. For example when `polymer build` is told to bundle everything into one html file, locales.json gets left out. This isn't too big of a problem but it has the following two cons:
1. `locales.json` may get angry and vengeful after being left out every single build.
2. It means an extra network request needs to be done.

Perhaps this could be solved simply by converting the `json` file into a javascript function that returns the locales data. e.g.

```
function login-fire-locales() {
  return { ...locales here ...};
}
```

I'm not sure what the 'recommended' localization method is for Polymer... I suppose I should figure that out soon.

**Comment by sbeleidy** [comment]
First of all, sorry for the late reply!

The reason we did locales.json is from https://www.polymer-project.org/1.0/toolbox/localize . The idea is also that you would have 1 main locales.json in your app for all your localization. I understand the issue of it not copying the locales.json file from login-fire but the problem is then you can't add your own locales.json.

A workaround for right now would be to copy the login-fire locales.json file into your app locales.json. 

The reason I don't like the function is because it means that if you want to change the values, you would have to do that inside the element.

What are your thoughts on that?

**Comment by sbeleidy** [comment]
@masonlouchart @bkawk, what are your thoughts on this?

**Comment by masonlouchart** [comment]
Yeah... loading a JS object through a HTML import could be nice.
